language: ruby
rvm:
  - 2.4
cache: bundler
script: ./scripts/build.sh
deploy:
  provider: pages
  skip_cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: build
  on: 2acoin-master
  fqdn: api-docs.2acoin.org
  verbose: true

before_install:
  - git clone https://github.com/2acoin/2acoin-docs.git 2acoin-docs

env:
  global:
    secure: MGGtebBgYQydCqNLIKt/KkQwdARlT3B+0ip03orEFqqSJVd1jR4guhs8JtZ8TEMwItn1Y7WzPdCccfn0QmI9XbsmUKrreBZmzq8KBD3ZlSxz/VJIRz2xj9OR0cj5F13aQ9zALWin1hwW/kPbLfWJkEOq1PdZHgoPNTDaindSz+uV2Q3CeUrIC6VPUb6Un1IBr9J33WwZjVQMEatZxwqgKCuqnoMLRot0RgkSFy+l6lJ9z9OgCYHAz8Nr39SDfdOnoWye1JqeYHJZ0udQP/dQ8UDOdnNWH0Zt81QBEdrhrmoJxQK2Yb1YM77wbjeP3Mz7PCri5HvKwZewLQ4zZK9SaWC0mJuZkiH8I9JogkEh3r0ZVAHUY/jyNsjq2fxh9kLJG4dtVhiLsVD/Ihco97cz9VlA1agZr/ZIan9WYFHkoh9VuQtrLt61s1RLOFeVW+BXKD+mcBXN88xwwWiR3FXSCiMONhZxpR+sPFBX08yYRXn+PeFE39STJpYH65BWjf9OUUHeIEyfjm7mwPmFOazX3VfDhzFP5ObcRlkF24hKJTc3bJdz+jXbjg6yHF1Bb8dNiNAcLGhVOensXTGcAw6nhE5HfgJsvqnSS8416z8+D45bLjduXBGY8YLs95uh3InMc+iUoe2aUA3dCryYu65xlmxVhjtmC3JDV9Gn6iXgIG4=

