language: ruby
rvm:
  - 2.4
cache: bundler
script: ./scripts/build.sh
deploy:
  provider: pages
  skip_cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: build
  on: 2acoin-master
  fqdn: api-docs.2acoin.org
  verbose: true

before_install:
  - git clone https://github.com/2acoin/2acoin-docs.git 2acoin-docs


