language: ruby
rvm:
  - 2.4
cache: bundler
script: ./scripts/build.sh
deploy:
  provider: pages
  skip_cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: build
  on: 2acoin-master
  fqdn: api-docs.2acoin.org
  verbose: true

before_install:
  - git clone https://github.com/2acoin/2acoin-docs.git 2acoin-docs

env:
  global:
    secure: GYQHTJO3Q8Fj5VARCqojy9D1XOE3YcO5/AfWNyJonf6FTg0vguuuUdnh0rBP9+OUgA+jVxZK85MIxJb2bZJSdVn0Jpn4G3bL+Be9g6HpYzpCG6eBX8xShPSGb3RvGTzPvVJ3QqqD7WbEhBwZVsuXlhy0z0AbPuvQIkV9k/xB3Vj/Fd//U8q24Zvh9/hg7lavCXLYZjwHpghAkipdYZJ8v/YH24KmOvLUx9UdSkSE2FiJ89k6bfKzynJeQi6l3eGwDLhhJQ/ocff1TngUtUAGRfgZESGrewF+oY/w1uVA84Me6lNErZmGrbHF7TgQ/PuepW0xSBiFUz1UyClpK1hdY3kGvvCJIDA4zbhp9rmElgwlcyWthYbXRENwQC3sn+3F529R/4UPtfIwlnSd2nTMKnEF42CdpNJENU0ib/zziYEKZ2LfTZU0m5GAjqWXEOPbQ8/cOOguz2wpfXpxotECpVEenKmWP4ixbwa3wEVZBle2ngga4iXxbltGY70WPLdHY4FYxIae0LOSk8NKSFY46S18rGZ2QxAkA15NK9QFaEGrRGfPHuZJnWeYtJOzhjnL0BZZ4vg+k/p1lGLNPGf+M31ASvb7saw26WLw9tAxb/u1YQc7ImDGBfc5OWWhqsQC9/tdcpKB/0EZtAMoEjuAAAZV6C0FyavmWWQfHVFOpK8=
