language: ruby
rvm:
  - 2.4
cache: bundler
script: ./scripts/build.sh
deploy:
  provider: pages
  skip_cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: build
  on: 2acoin-master
  fqdn: api-docs.2acoin.org
  verbose: true

before_install:
  - git clone https://github.com/2acoin/2acoin-docs.git 2acoin-docs

env:
  global:
  - secure: xQiofDy8656TU6rVmNMFrTwl+bvFJQ8XgGv4pLrbZwhFzJEMEGKxMZNnPqO+S17sAgaiAFxN6ZHsirt9/OmKQ/5gIEv2UVCBHZHNtoQi/hXTAmM89GRJq4sM/rgN5EwxmfOGzBophZtqCEXLl6I3Yb3jbG3Gf4hdcgEW6UBG/GHqPow9+2NujoXonjuU5iC32zl0+7v12vbR7EeruPBjsP2M9mCdBuGCkpCCSGTQynlOmvU5hhPwMKt0jd2X0OumNkzNooxMRGrCirDde+OYpxenSfod4gtpHz96JZeOE3a19R4o9iey5r3O1MzQv8dv4Q7C7JBfvI+oFxDO+xoozcMBDKD+G2HMycm4DIncEvlQzIZrR/YUELfcJRb320twwNVQ3OtgwpkqvJi1HHNoXrd+CcTR6IEtP3RbbDPYGKxy9fBWLr1vF4WYopxNrOcpPPnqQcftms4aTedsMWF2bSxconSRK6o8iiN8bOp4dw1ucEEfoDIyd2kKjciqZ8Ra3jsopuCAgHIvXHmmHzRXZazYvKm92hcbZabfrNi8VGgPf7Gb8zueXt/ucUG20OWcWg3xKFynKWTWzl3+JftpzTa33+bv2gCLtQHuwMpOKByxsEesaGSlwgy5GT2lBjJdPLapUCEDFP7KBQNvOmOd2N3eWVUnnUBWxiEjouh3uUg=

