language: ruby
rvm:
  - 2.4
cache: bundler
script: ./scripts/build.sh
deploy:
  provider: pages
  skip_cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: build
  on: 2acoin-master
  fqdn: api-docs.2acoin.org
  verbose: true

before_install:
  - git clone https://github.com/2acoin/2acoin-docs.git 2acoin-docs

env:
  global:
    secure: O8KfGyqB4TY66iBCvxBznv6DSbRRj08ApPjiUyC4fTSmZIhOvUdFn0HJos9L2slntE/cycqIhhirakNEvAr84WvmGHW60nf+T/9uF9QXYCP+eSOqJ0BZTUdneBu3FdDVUKE7S8Hwj5AMueShCRvTqsFOPhEJ4Vz0HdesyHduEMzDozsHomWBphqnTDWLAtBZrXGxnGgYimM2R8goc1zKKhE8M6lFVGj5hVYKO63Q8e0+TR4NG/OR73w001Zo9X0EE2fFvK43Bqb+1wi0970z89H7bOgH9RmjLBGnG9dZrQSaJZKneM0yh1WOedZPtu8h1g/TE2fnZDCQVHwCwA1H2O3Egs4h0aQlwWgmHeR55ep6e5H2e/a7aF/t9lD/ayKvHJ2JxzOhRQa9sMSsZt1j5EhDfGtqMZpWJnXLnfgIj2CBntMJxd0HmzT8ok3HsUvLn2qS4rrNYGIXiHchVreCb96ZNvchZW0/0q1FJCQtrPHMPP57c4v7wYat/srt8ViJEOj94FBEf7AQRY25atXaHedu5nvaXPXoCcfTBYeNPJIMZ1GzSd9wKAPN204i1UtWUV8bcw7kTOKmPfkM13Q8ycGwz6KHz+Z7FgBu92iXLpho7+aW2eXfrYs8gC2zbS/ZmyVoFCwujsbjb7a0ssjmMDZIkSKubsRz70BDJR4wx+A=
